apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-app
  template:
    metadata:
      labels:
        app: pod-app
    spec:
      containers:
        - name: pod-app
          image: maharnackademin/pod-app:1.0
          ports:
            - containerPort: 3000
