apiVersion: v1
kind: Service
metadata:
  name: pod-app-service
spec:
  type: NodePort
  selector:
    app: pod-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
